# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Apr  4 00:32:40 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 537)
        MainWindow.setMaximumSize(QtCore.QSize(784, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalFrame = QtGui.QFrame(self.centralwidget)
        self.verticalFrame.setMaximumSize(QtCore.QSize(244, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_move = QtGui.QGroupBox(self.verticalFrame)
        self.group_move.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_move.setFlat(False)
        self.group_move.setObjectName("group_move")
        self.gridLayout = QtGui.QGridLayout(self.group_move)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_speed_right = QtGui.QSlider(self.group_move)
        self.slider_speed_right.setMinimum(-255)
        self.slider_speed_right.setMaximum(255)
        self.slider_speed_right.setSingleStep(16)
        self.slider_speed_right.setPageStep(32)
        self.slider_speed_right.setSliderPosition(0)
        self.slider_speed_right.setOrientation(QtCore.Qt.Vertical)
        self.slider_speed_right.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_speed_right.setTickInterval(63)
        self.slider_speed_right.setObjectName("slider_speed_right")
        self.gridLayout.addWidget(self.slider_speed_right, 0, 1, 3, 1)
        self.button_move_stop = QtGui.QPushButton(self.group_move)
        self.button_move_stop.setObjectName("button_move_stop")
        self.gridLayout.addWidget(self.button_move_stop, 1, 3, 1, 1)
        self.button_move_backward = QtGui.QPushButton(self.group_move)
        self.button_move_backward.setObjectName("button_move_backward")
        self.gridLayout.addWidget(self.button_move_backward, 2, 3, 1, 1)
        self.button_move_left = QtGui.QPushButton(self.group_move)
        self.button_move_left.setObjectName("button_move_left")
        self.gridLayout.addWidget(self.button_move_left, 1, 2, 1, 1)
        self.button_move_right = QtGui.QPushButton(self.group_move)
        self.button_move_right.setObjectName("button_move_right")
        self.gridLayout.addWidget(self.button_move_right, 1, 4, 1, 1)
        self.button_move_forward = QtGui.QPushButton(self.group_move)
        self.button_move_forward.setObjectName("button_move_forward")
        self.gridLayout.addWidget(self.button_move_forward, 0, 3, 1, 1)
        self.slider_speed_left = QtGui.QSlider(self.group_move)
        self.slider_speed_left.setMinimum(-255)
        self.slider_speed_left.setMaximum(255)
        self.slider_speed_left.setSingleStep(16)
        self.slider_speed_left.setPageStep(32)
        self.slider_speed_left.setSliderPosition(0)
        self.slider_speed_left.setOrientation(QtCore.Qt.Vertical)
        self.slider_speed_left.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_speed_left.setTickInterval(63)
        self.slider_speed_left.setObjectName("slider_speed_left")
        self.gridLayout.addWidget(self.slider_speed_left, 0, 0, 3, 1)
        self.lcd_speed_left = QtGui.QLCDNumber(self.group_move)
        self.lcd_speed_left.setObjectName("lcd_speed_left")
        self.gridLayout.addWidget(self.lcd_speed_left, 0, 2, 1, 1)
        self.lcd_speed_right = QtGui.QLCDNumber(self.group_move)
        self.lcd_speed_right.setProperty("intValue", 0)
        self.lcd_speed_right.setObjectName("lcd_speed_right")
        self.gridLayout.addWidget(self.lcd_speed_right, 0, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.group_move)
        self.group_belt = QtGui.QGroupBox(self.verticalFrame)
        self.group_belt.setObjectName("group_belt")
        self.verticalLayout = QtGui.QVBoxLayout(self.group_belt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slider_belt_speed = QtGui.QSlider(self.group_belt)
        self.slider_belt_speed.setMinimum(0)
        self.slider_belt_speed.setMaximum(255)
        self.slider_belt_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_belt_speed.setObjectName("slider_belt_speed")
        self.horizontalLayout_4.addWidget(self.slider_belt_speed)
        self.lcd_belt_speed = QtGui.QLCDNumber(self.group_belt)
        self.lcd_belt_speed.setObjectName("lcd_belt_speed")
        self.horizontalLayout_4.addWidget(self.lcd_belt_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_belt_start = QtGui.QPushButton(self.group_belt)
        self.button_belt_start.setObjectName("button_belt_start")
        self.horizontalLayout_5.addWidget(self.button_belt_start)
        self.button_belt_stop = QtGui.QPushButton(self.group_belt)
        self.button_belt_stop.setObjectName("button_belt_stop")
        self.horizontalLayout_5.addWidget(self.button_belt_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.group_belt)
        self.group_bucket = QtGui.QGroupBox(self.verticalFrame)
        self.group_bucket.setObjectName("group_bucket")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.group_bucket)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_bucket_down = QtGui.QPushButton(self.group_bucket)
        self.button_bucket_down.setObjectName("button_bucket_down")
        self.horizontalLayout_2.addWidget(self.button_bucket_down)
        self.button_bucket_stop = QtGui.QPushButton(self.group_bucket)
        self.button_bucket_stop.setObjectName("button_bucket_stop")
        self.horizontalLayout_2.addWidget(self.button_bucket_stop)
        self.button_bucket_up = QtGui.QPushButton(self.group_bucket)
        self.button_bucket_up.setObjectName("button_bucket_up")
        self.horizontalLayout_2.addWidget(self.button_bucket_up)
        self.verticalLayout_3.addWidget(self.group_bucket)
        self.group_states = QtGui.QGroupBox(self.verticalFrame)
        self.group_states.setObjectName("group_states")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.group_states)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_state_move = QtGui.QRadioButton(self.group_states)
        self.radio_state_move.setObjectName("radio_state_move")
        self.verticalLayout_4.addWidget(self.radio_state_move)
        self.radio_state_dig = QtGui.QRadioButton(self.group_states)
        self.radio_state_dig.setObjectName("radio_state_dig")
        self.verticalLayout_4.addWidget(self.radio_state_dig)
        self.radio_state_dump = QtGui.QRadioButton(self.group_states)
        self.radio_state_dump.setObjectName("radio_state_dump")
        self.verticalLayout_4.addWidget(self.radio_state_dump)
        self.verticalLayout_3.addWidget(self.group_states)
        self.button_panic = QtGui.QPushButton(self.verticalFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.button_panic.setPalette(palette)
        self.button_panic.setObjectName("button_panic")
        self.verticalLayout_3.addWidget(self.button_panic)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_7.addWidget(self.verticalFrame)
        self.verticalFrame_2 = QtGui.QFrame(self.centralwidget)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.group_msg = QtGui.QTabWidget(self.verticalFrame_2)
        self.group_msg.setObjectName("group_msg")
        self.tab_msg_all = QtGui.QWidget()
        self.tab_msg_all.setObjectName("tab_msg_all")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_msg_all)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.text_msg_all = QtGui.QTextBrowser(self.tab_msg_all)
        self.text_msg_all.setObjectName("text_msg_all")
        self.gridLayout_3.addWidget(self.text_msg_all, 0, 0, 1, 1)
        self.group_msg.addTab(self.tab_msg_all, "")
        self.tab_msg_error = QtGui.QWidget()
        self.tab_msg_error.setObjectName("tab_msg_error")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_msg_error)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.text_msg_error = QtGui.QTextBrowser(self.tab_msg_error)
        self.text_msg_error.setObjectName("text_msg_error")
        self.gridLayout_4.addWidget(self.text_msg_error, 0, 0, 1, 1)
        self.group_msg.addTab(self.tab_msg_error, "")
        self.verticalLayout_5.addWidget(self.group_msg)
        self.group_timer = QtGui.QGroupBox(self.verticalFrame_2)
        self.group_timer.setObjectName("group_timer")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.group_timer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.progressBar = QtGui.QProgressBar(self.group_timer)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtGui.QPushButton(self.group_timer)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.group_timer)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.spinBox = QtGui.QSpinBox(self.group_timer)
        self.spinBox.setProperty("value", 15)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.label = QtGui.QLabel(self.group_timer)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.group_timer)
        self.horizontalLayout_7.addWidget(self.verticalFrame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnection = QtGui.QAction(MainWindow)
        self.actionConnection.setObjectName("actionConnection")
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")

        self.retranslateUi(MainWindow)
        self.group_msg.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lunarbot Contoller", None, QtGui.QApplication.UnicodeUTF8))
        self.group_move.setTitle(QtGui.QApplication.translate("MainWindow", "Movement", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_stop.setText(QtGui.QApplication.translate("MainWindow", "[ ]", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_backward.setText(QtGui.QApplication.translate("MainWindow", "\\/", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_left.setText(QtGui.QApplication.translate("MainWindow", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_right.setText(QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_forward.setText(QtGui.QApplication.translate("MainWindow", "/\\", None, QtGui.QApplication.UnicodeUTF8))
        self.group_belt.setTitle(QtGui.QApplication.translate("MainWindow", "Belt Digger Head", None, QtGui.QApplication.UnicodeUTF8))
        self.button_belt_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.button_belt_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.group_bucket.setTitle(QtGui.QApplication.translate("MainWindow", "Bucket", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bucket_down.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bucket_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bucket_up.setText(QtGui.QApplication.translate("MainWindow", "Raise", None, QtGui.QApplication.UnicodeUTF8))
        self.group_states.setTitle(QtGui.QApplication.translate("MainWindow", "Lunarbot State", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_state_move.setText(QtGui.QApplication.translate("MainWindow", "Manuever", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_state_dig.setText(QtGui.QApplication.translate("MainWindow", "Dig", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_state_dump.setText(QtGui.QApplication.translate("MainWindow", "Dump Bucket", None, QtGui.QApplication.UnicodeUTF8))
        self.button_panic.setText(QtGui.QApplication.translate("MainWindow", "Don\'t Panic", None, QtGui.QApplication.UnicodeUTF8))
        self.group_msg.setTabText(self.group_msg.indexOf(self.tab_msg_all), QtGui.QApplication.translate("MainWindow", "All Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.group_msg.setTabText(self.group_msg.indexOf(self.tab_msg_error), QtGui.QApplication.translate("MainWindow", "Error Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.group_timer.setTitle(QtGui.QApplication.translate("MainWindow", "Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setText(QtGui.QApplication.translate("MainWindow", "connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "options", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Apr 11 09:10:41 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 537)
        MainWindow.setMaximumSize(QtCore.QSize(784, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalFrame = QtGui.QFrame(self.centralwidget)
        self.verticalFrame.setMaximumSize(QtCore.QSize(244, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_move = QtGui.QGroupBox(self.verticalFrame)
        self.group_move.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_move.setFlat(False)
        self.group_move.setObjectName("group_move")
        self.gridLayout = QtGui.QGridLayout(self.group_move)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_speed_right = QtGui.QSlider(self.group_move)
        self.slider_speed_right.setMinimum(-255)
        self.slider_speed_right.setMaximum(255)
        self.slider_speed_right.setSingleStep(16)
        self.slider_speed_right.setPageStep(32)
        self.slider_speed_right.setSliderPosition(0)
        self.slider_speed_right.setOrientation(QtCore.Qt.Vertical)
        self.slider_speed_right.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_speed_right.setTickInterval(63)
        self.slider_speed_right.setObjectName("slider_speed_right")
        self.gridLayout.addWidget(self.slider_speed_right, 0, 1, 3, 1)
        self.button_move_stop = QtGui.QPushButton(self.group_move)
        self.button_move_stop.setObjectName("button_move_stop")
        self.gridLayout.addWidget(self.button_move_stop, 1, 3, 1, 1)
        self.button_move_backward = QtGui.QPushButton(self.group_move)
        self.button_move_backward.setObjectName("button_move_backward")
        self.gridLayout.addWidget(self.button_move_backward, 2, 3, 1, 1)
        self.button_move_left = QtGui.QPushButton(self.group_move)
        self.button_move_left.setObjectName("button_move_left")
        self.gridLayout.addWidget(self.button_move_left, 1, 2, 1, 1)
        self.button_move_right = QtGui.QPushButton(self.group_move)
        self.button_move_right.setObjectName("button_move_right")
        self.gridLayout.addWidget(self.button_move_right, 1, 4, 1, 1)
        self.button_move_forward = QtGui.QPushButton(self.group_move)
        self.button_move_forward.setObjectName("button_move_forward")
        self.gridLayout.addWidget(self.button_move_forward, 0, 3, 1, 1)
        self.slider_speed_left = QtGui.QSlider(self.group_move)
        self.slider_speed_left.setMinimum(-255)
        self.slider_speed_left.setMaximum(255)
        self.slider_speed_left.setSingleStep(16)
        self.slider_speed_left.setPageStep(32)
        self.slider_speed_left.setSliderPosition(0)
        self.slider_speed_left.setOrientation(QtCore.Qt.Vertical)
        self.slider_speed_left.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_speed_left.setTickInterval(63)
        self.slider_speed_left.setObjectName("slider_speed_left")
        self.gridLayout.addWidget(self.slider_speed_left, 0, 0, 3, 1)
        self.lcd_speed_left = QtGui.QLCDNumber(self.group_move)
        self.lcd_speed_left.setObjectName("lcd_speed_left")
        self.gridLayout.addWidget(self.lcd_speed_left, 0, 2, 1, 1)
        self.lcd_speed_right = QtGui.QLCDNumber(self.group_move)
        self.lcd_speed_right.setProperty("intValue", 0)
        self.lcd_speed_right.setObjectName("lcd_speed_right")
        self.gridLayout.addWidget(self.lcd_speed_right, 0, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.group_move)
        self.group_belt = QtGui.QGroupBox(self.verticalFrame)
        self.group_belt.setObjectName("group_belt")
        self.verticalLayout = QtGui.QVBoxLayout(self.group_belt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slider_belt_speed = QtGui.QSlider(self.group_belt)
        self.slider_belt_speed.setMinimum(0)
        self.slider_belt_speed.setMaximum(255)
        self.slider_belt_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_belt_speed.setObjectName("slider_belt_speed")
        self.horizontalLayout_4.addWidget(self.slider_belt_speed)
        self.lcd_belt_speed = QtGui.QLCDNumber(self.group_belt)
        self.lcd_belt_speed.setObjectName("lcd_belt_speed")
        self.horizontalLayout_4.addWidget(self.lcd_belt_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_belt_start = QtGui.QPushButton(self.group_belt)
        self.button_belt_start.setObjectName("button_belt_start")
        self.horizontalLayout_5.addWidget(self.button_belt_start)
        self.button_belt_stop = QtGui.QPushButton(self.group_belt)
        self.button_belt_stop.setObjectName("button_belt_stop")
        self.horizontalLayout_5.addWidget(self.button_belt_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.group_belt)
        self.group_bucket = QtGui.QGroupBox(self.verticalFrame)
        self.group_bucket.setObjectName("group_bucket")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.group_bucket)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_bucket_down = QtGui.QPushButton(self.group_bucket)
        self.button_bucket_down.setObjectName("button_bucket_down")
        self.horizontalLayout_2.addWidget(self.button_bucket_down)
        self.button_bucket_stop = QtGui.QPushButton(self.group_bucket)
        self.button_bucket_stop.setObjectName("button_bucket_stop")
        self.horizontalLayout_2.addWidget(self.button_bucket_stop)
        self.button_bucket_up = QtGui.QPushButton(self.group_bucket)
        self.button_bucket_up.setObjectName("button_bucket_up")
        self.horizontalLayout_2.addWidget(self.button_bucket_up)
        self.verticalLayout_3.addWidget(self.group_bucket)
        self.group_joystick = QtGui.QGroupBox(self.verticalFrame)
        self.group_joystick.setObjectName("group_joystick")
        self.horizontalLayout = QtGui.QHBoxLayout(self.group_joystick)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_joystick_enable = QtGui.QCheckBox(self.group_joystick)
        self.check_joystick_enable.setObjectName("check_joystick_enable")
        self.horizontalLayout.addWidget(self.check_joystick_enable)
        self.verticalLayout_3.addWidget(self.group_joystick)
        self.group_states = QtGui.QGroupBox(self.verticalFrame)
        self.group_states.setObjectName("group_states")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.group_states)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_state_move = QtGui.QRadioButton(self.group_states)
        self.radio_state_move.setObjectName("radio_state_move")
        self.verticalLayout_4.addWidget(self.radio_state_move)
        self.radio_state_dig = QtGui.QRadioButton(self.group_states)
        self.radio_state_dig.setObjectName("radio_state_dig")
        self.verticalLayout_4.addWidget(self.radio_state_dig)
        self.radio_state_dump = QtGui.QRadioButton(self.group_states)
        self.radio_state_dump.setObjectName("radio_state_dump")
        self.verticalLayout_4.addWidget(self.radio_state_dump)
        self.verticalLayout_3.addWidget(self.group_states)
        self.button_panic = QtGui.QPushButton(self.verticalFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 2, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.button_panic.setPalette(palette)
        self.button_panic.setObjectName("button_panic")
        self.verticalLayout_3.addWidget(self.button_panic)
        self.horizontalLayout_7.addWidget(self.verticalFrame)
        self.verticalFrame_2 = QtGui.QFrame(self.centralwidget)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.group_msg = QtGui.QTabWidget(self.verticalFrame_2)
        self.group_msg.setObjectName("group_msg")
        self.tab_msg_all = QtGui.QWidget()
        self.tab_msg_all.setObjectName("tab_msg_all")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_msg_all)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.text_msg_all = QtGui.QTextBrowser(self.tab_msg_all)
        self.text_msg_all.setObjectName("text_msg_all")
        self.gridLayout_3.addWidget(self.text_msg_all, 0, 0, 1, 1)
        self.group_msg.addTab(self.tab_msg_all, "")
        self.tab_msg_error = QtGui.QWidget()
        self.tab_msg_error.setObjectName("tab_msg_error")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_msg_error)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.text_msg_error = QtGui.QTextBrowser(self.tab_msg_error)
        self.text_msg_error.setObjectName("text_msg_error")
        self.gridLayout_4.addWidget(self.text_msg_error, 0, 0, 1, 1)
        self.group_msg.addTab(self.tab_msg_error, "")
        self.verticalLayout_5.addWidget(self.group_msg)
        self.group_timer = QtGui.QGroupBox(self.verticalFrame_2)
        self.group_timer.setObjectName("group_timer")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.group_timer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.progressBar = QtGui.QProgressBar(self.group_timer)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtGui.QPushButton(self.group_timer)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.group_timer)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.spinBox = QtGui.QSpinBox(self.group_timer)
        self.spinBox.setProperty("value", 15)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.label = QtGui.QLabel(self.group_timer)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.group_timer)
        self.horizontalLayout_7.addWidget(self.verticalFrame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnection = QtGui.QAction(MainWindow)
        self.actionConnection.setObjectName("actionConnection")
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")

        self.retranslateUi(MainWindow)
        self.group_msg.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lunarbot Contoller", None, QtGui.QApplication.UnicodeUTF8))
        self.group_move.setTitle(QtGui.QApplication.translate("MainWindow", "Movement", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_stop.setText(QtGui.QApplication.translate("MainWindow", "[ ]", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_backward.setText(QtGui.QApplication.translate("MainWindow", "\\/", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_left.setText(QtGui.QApplication.translate("MainWindow", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_right.setText(QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_forward.setText(QtGui.QApplication.translate("MainWindow", "/\\", None, QtGui.QApplication.UnicodeUTF8))
        self.group_belt.setTitle(QtGui.QApplication.translate("MainWindow", "Belt Digger Head", None, QtGui.QApplication.UnicodeUTF8))
        self.button_belt_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.button_belt_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.group_bucket.setTitle(QtGui.QApplication.translate("MainWindow", "Bucket", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bucket_down.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bucket_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bucket_up.setText(QtGui.QApplication.translate("MainWindow", "Raise", None, QtGui.QApplication.UnicodeUTF8))
        self.group_joystick.setTitle(QtGui.QApplication.translate("MainWindow", "Joystick", None, QtGui.QApplication.UnicodeUTF8))
        self.check_joystick_enable.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.group_states.setTitle(QtGui.QApplication.translate("MainWindow", "Lunarbot State", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_state_move.setText(QtGui.QApplication.translate("MainWindow", "Manuever", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_state_dig.setText(QtGui.QApplication.translate("MainWindow", "Dig", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_state_dump.setText(QtGui.QApplication.translate("MainWindow", "Dump Bucket", None, QtGui.QApplication.UnicodeUTF8))
        self.button_panic.setText(QtGui.QApplication.translate("MainWindow", "Don\'t Panic", None, QtGui.QApplication.UnicodeUTF8))
        self.group_msg.setTabText(self.group_msg.indexOf(self.tab_msg_all), QtGui.QApplication.translate("MainWindow", "All Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.group_msg.setTabText(self.group_msg.indexOf(self.tab_msg_error), QtGui.QApplication.translate("MainWindow", "Error Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.group_timer.setTitle(QtGui.QApplication.translate("MainWindow", "Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setText(QtGui.QApplication.translate("MainWindow", "connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "options", None, QtGui.QApplication.UnicodeUTF8))

