# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt4Gui.ui'
#
# Created: Mon Mar 15 20:12:08 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 204)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 591, 157))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.motorSpeedSliderLeft = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.motorSpeedSliderLeft.setMinimum(-256)
        self.motorSpeedSliderLeft.setMaximum(256)
        self.motorSpeedSliderLeft.setSingleStep(32)
        self.motorSpeedSliderLeft.setPageStep(32)
        self.motorSpeedSliderLeft.setOrientation(QtCore.Qt.Vertical)
        self.motorSpeedSliderLeft.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motorSpeedSliderLeft.setTickInterval(256)
        self.motorSpeedSliderLeft.setObjectName("motorSpeedSliderLeft")
        self.horizontalLayout.addWidget(self.motorSpeedSliderLeft)
        self.motorSpeedLable = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.motorSpeedLable.setObjectName("motorSpeedLable")
        self.horizontalLayout.addWidget(self.motorSpeedLable)
        self.motorSpeedSliderRight = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.motorSpeedSliderRight.setMinimum(-256)
        self.motorSpeedSliderRight.setMaximum(256)
        self.motorSpeedSliderRight.setSingleStep(32)
        self.motorSpeedSliderRight.setPageStep(32)
        self.motorSpeedSliderRight.setOrientation(QtCore.Qt.Vertical)
        self.motorSpeedSliderRight.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motorSpeedSliderRight.setTickInterval(256)
        self.motorSpeedSliderRight.setObjectName("motorSpeedSliderRight")
        self.horizontalLayout.addWidget(self.motorSpeedSliderRight)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.movStopButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.movStopButton.setObjectName("movStopButton")
        self.gridLayout.addWidget(self.movStopButton, 1, 1, 1, 1)
        self.movBackButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.movBackButton.setObjectName("movBackButton")
        self.gridLayout.addWidget(self.movBackButton, 2, 1, 1, 1)
        self.movForwardButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.movForwardButton.setObjectName("movForwardButton")
        self.gridLayout.addWidget(self.movForwardButton, 0, 1, 1, 1)
        self.movLeftButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.movLeftButton.setObjectName("movLeftButton")
        self.gridLayout.addWidget(self.movLeftButton, 1, 0, 1, 1)
        self.movRightButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.movRightButton.setObjectName("movRightButton")
        self.gridLayout.addWidget(self.movRightButton, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.debugInfoText = QtGui.QTextBrowser(self.verticalLayoutWidget_2)
        self.debugInfoText.setObjectName("debugInfoText")
        self.horizontalLayout.addWidget(self.debugInfoText)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.menubar.setObjectName("menubar")
        self.menuConnection = QtGui.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReconnect = QtGui.QAction(MainWindow)
        self.actionReconnect.setObjectName("actionReconnect")
        self.actionReconnect_2 = QtGui.QAction(MainWindow)
        self.actionReconnect_2.setObjectName("actionReconnect_2")
        self.menuConnection.addAction(self.actionReconnect)
        self.menuConnection.addAction(self.actionReconnect_2)
        self.menubar.addAction(self.menuConnection.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.movLeftButton, QtCore.SIGNAL("clicked()"), self.motorSpeedSliderLeft.addStep)
        QtCore.QObject.connect(self.movLeftButton, QtCore.SIGNAL("clicked()"), self.motorSpeedSliderRight.subtractStep)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.motorSpeedLable.setText(QtGui.QApplication.translate("MainWindow", "Motor\n"
"Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.movStopButton.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.movBackButton.setText(QtGui.QApplication.translate("MainWindow", "back", None, QtGui.QApplication.UnicodeUTF8))
        self.movForwardButton.setText(QtGui.QApplication.translate("MainWindow", "forward", None, QtGui.QApplication.UnicodeUTF8))
        self.movLeftButton.setText(QtGui.QApplication.translate("MainWindow", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.movRightButton.setText(QtGui.QApplication.translate("MainWindow", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConnection.setTitle(QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReconnect.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReconnect_2.setText(QtGui.QApplication.translate("MainWindow", "Reconnect", None, QtGui.QApplication.UnicodeUTF8))

